<?php

return [
    'en' => [
        'feedback.you_said_letter' => 'You said {spoken}.',
        'feedback.you_said_transcript' => 'You said {final}.',
        'feedback.unclear_letter' => 'I did not hear a clear letter. You can try the next one.',
        'feedback.unclear_phrase' => 'I did not hear a clear phrase. You can try the next one.',
        'feedback.unclear_sentence' => 'I did not hear a clear sentence. You can try the next one.',
        'feedback.unclear_word' => 'I did not hear a clear word. You can try the next one.',
        'alignment.missing_word' => 'You missed the word {expected}.',
        'alignment.missing_word_fallback' => 'You missed one word. Let us try the {unit} again.',
        'alignment.extra_word' => 'I heard an extra word, {actual}.',
        'alignment.extra_word_fallback' => 'I heard one extra word. Let us try the {unit} again.',
        'alignment.replaced_word' => 'I heard {actual} instead of {expected}.',
        'alignment.replaced_word_fallback' => 'One word was different. Let us try the {unit} again.',
        'alignment.words_out_of_order' => 'The words {first} and {second} changed places.',
        'alignment.words_out_of_order_fallback' => 'Two words changed places. Let us try the phrase again.',
        'alignment.multiple_missing_word' => 'Let us fix one part. You missed the word {expected}.',
        'alignment.multiple_missing_word_fallback' => 'Let us fix one part. One word was missing.',
        'alignment.multiple_extra_word' => 'Let us fix one part. I heard an extra word, {actual}.',
        'alignment.multiple_extra_word_fallback' => 'Let us fix one part. I heard an extra word.',
        'alignment.multiple_replaced_word' => 'Let us fix one part. I heard {actual} instead of {expected}.',
        'alignment.multiple_replaced_word_fallback' => 'Let us fix one part. One word was different.',
        'alignment.multiple_default' => 'Some words were different. Let us read the phrase one word at a time.',
        'alignment.default' => 'Some words were different. Let us read the {unit} one word at a time.',
        'demonstration.lesson_2_word' => 'The word is {word}. Listen: {word}. Now you try.',
    ],
    'fil-PH' => [
        'feedback.you_said_letter' => 'Ang sinabi mo ay {spoken}.',
        'feedback.you_said_transcript' => 'Ang sinabi mo ay {final}.',
        'feedback.unclear_letter' => 'Hindi ako nakarinig ng malinaw na letra. Maaari mong subukan ang susunod.',
        'feedback.unclear_phrase' => 'Hindi ako nakarinig ng malinaw na parirala. Maaari mong subukan ang susunod.',
        'feedback.unclear_sentence' => 'Hindi ako nakarinig ng malinaw na pangungusap. Maaari mong subukan ang susunod.',
        'feedback.unclear_word' => 'Hindi ako nakarinig ng malinaw na salita. Maaari mong subukan ang susunod.',
        'alignment.missing_word' => 'Hindi mo nasabi ang salitang {expected}.',
        'alignment.missing_word_fallback' => 'May isang salitang hindi mo nasabi. Subukan nating muli ang {unit}.',
        'alignment.extra_word' => 'May narinig akong sobrang salita, {actual}.',
        'alignment.extra_word_fallback' => 'May narinig akong isang sobrang salita. Subukan nating muli ang {unit}.',
        'alignment.replaced_word' => 'Narinig ko ang {actual} sa halip na {expected}.',
        'alignment.replaced_word_fallback' => 'May isang salitang naiiba. Subukan nating muli ang {unit}.',
        'alignment.words_out_of_order' => 'Nagpalit ng puwesto ang mga salitang {first} at {second}.',
        'alignment.words_out_of_order_fallback' => 'Nagpalit ng puwesto ang dalawang salita. Subukan nating muli ang parirala.',
        'alignment.multiple_missing_word' => 'Ayusin natin ang isang bahagi. Hindi mo nasabi ang salitang {expected}.',
        'alignment.multiple_missing_word_fallback' => 'Ayusin natin ang isang bahagi. May isang salitang nawawala.',
        'alignment.multiple_extra_word' => 'Ayusin natin ang isang bahagi. May narinig akong sobrang salita, {actual}.',
        'alignment.multiple_extra_word_fallback' => 'Ayusin natin ang isang bahagi. May narinig akong sobrang salita.',
        'alignment.multiple_replaced_word' => 'Ayusin natin ang isang bahagi. Narinig ko ang {actual} sa halip na {expected}.',
        'alignment.multiple_replaced_word_fallback' => 'Ayusin natin ang isang bahagi. May isang salitang naiiba.',
        'alignment.multiple_default' => 'May ilang salitang naiiba. Basahin natin ang parirala nang paisa-isang salita.',
        'alignment.default' => 'May ilang salitang naiiba. Basahin natin ang {unit} nang paisa-isang salita.',
        'demonstration.lesson_2_word' => 'Ang salita ay {word}. Makinig: {word}. Ngayon, ikaw naman.',
    ],
];
