export type WordRescueAssetReviewStatus =
  "draft" | "needs_review" | "approved" | "rejected";

export type WordRescueAssetReviewRecord = {
  contentId: string;
  targetWord: string;
  visualKey: string;
  visualKind: "image" | "icon";
  file: `assets/vocabulary/${string}.webp`;
  width: number;
  height: number;
  byteSize: number;
  intendedMeaning: string;
  altGuidance: string;
  disambiguationNote: string;
  contextualCue?: string;
  dominantVisualSubject?: string;
  supportingSubjects?: string;
  targetDominance?: "pass" | "risk";
  childSafetyInclusionNote?: string;
  reviewStatus: WordRescueAssetReviewStatus;
  reviewerNote: string;
  provenanceLicenseNote: string;
};

const batchAReviewNote =
  "Batch A approved by human visual review; final accessibility wording and publication provenance remain tracked separately.";
const batchBReviewNote =
  "Batch B generated draft; human visual, accessibility, and curriculum review is still required.";
const batchBApprovalNote =
  "Batch B asset approved by human visual review; final accessibility wording and publication provenance remain tracked separately.";
const iconBatchAApprovalNote =
  "Human-approved Icon Batch A asset; content binding, target clarity, child safety, and provenance metadata preserved.";
const iconBatchAJogRevisionNote =
  "Icon Batch A JOG replacement draft; human visual, accessibility, curriculum, target-dominance, and provenance review is required.";
const batchCApprovalNote =
  "Batch C asset approved by human visual review; final accessibility wording and publication provenance remain tracked separately.";
const provenanceNote =
  "AI-generated draft via the built-in image generation workflow; final provenance and license record required before publication.";

export const wordRescueAssetReview = {
  "word-bag": {
    contentId: "lesson-v1-word-bag",
    targetWord: "bag",
    visualKey: "word-bag",
    visualKind: "image",
    file: "assets/vocabulary/word-bag.webp",
    width: 1254,
    height: 1254,
    byteSize: 55958,
    intendedMeaning: "A plain school bag.",
    altGuidance: "A plain bag",
    disambiguationNote: "Use a simple school bag with no brand marks.",
    reviewStatus: "approved",
    reviewerNote: batchAReviewNote,
    provenanceLicenseNote: provenanceNote,
  },
  "word-bat": {
    contentId: "lesson-v1-word-bat",
    targetWord: "bat",
    visualKey: "word-bat",
    visualKind: "icon",
    file: "assets/vocabulary/word-bat.webp",
    width: 1402,
    height: 1122,
    byteSize: 54892,
    intendedMeaning: "A small flying animal bat.",
    altGuidance: "A small flying animal bat",
    disambiguationNote: "Depict the animal and not sports equipment.",
    contextualCue:
      "Spread wings, ears, and a flying pose identify the animal bat.",
    dominantVisualSubject: "The flying animal bat",
    supportingSubjects: "None",
    targetDominance: "pass",
    childSafetyInclusionNote:
      "Friendly non-scary animal presentation with no horror, blood, or sports-violence cues.",
    reviewStatus: "approved",
    reviewerNote: iconBatchAApprovalNote,
    provenanceLicenseNote: provenanceNote,
  },
  "word-bed": {
    contentId: "lesson-v1-word-bed",
    targetWord: "bed",
    visualKey: "word-bed",
    visualKind: "image",
    file: "assets/vocabulary/word-bed.webp",
    width: 1329,
    height: 1183,
    byteSize: 45880,
    intendedMeaning: "A simple bed with a plain blanket.",
    altGuidance: "A simple bed",
    disambiguationNote: "Use a plain bed with no extra written clues.",
    reviewStatus: "approved",
    reviewerNote: batchAReviewNote,
    provenanceLicenseNote: provenanceNote,
  },
  "word-cap": {
    contentId: "lesson-v1-word-cap",
    targetWord: "cap",
    visualKey: "word-cap",
    visualKind: "image",
    file: "assets/vocabulary/word-cap.webp",
    width: 1254,
    height: 1254,
    byteSize: 39724,
    intendedMeaning: "A simple brimmed cap.",
    altGuidance: "A simple brimmed cap",
    disambiguationNote: "Keep the cap distinct from a general hat.",
    reviewStatus: "approved",
    reviewerNote: batchAReviewNote,
    provenanceLicenseNote: provenanceNote,
  },
  "word-can": {
    contentId: "lesson-v1-word-can",
    targetWord: "can",
    visualKey: "word-can",
    visualKind: "icon",
    file: "assets/vocabulary/word-can.webp",
    width: 1254,
    height: 1254,
    byteSize: 39842,
    intendedMeaning: "A plain tin can.",
    altGuidance: "A plain tin can",
    disambiguationNote: "Depict a container and not the modal verb.",
    contextualCue:
      "The open rim and cylindrical container shape provide the object meaning.",
    dominantVisualSubject: "The plain tin can",
    supportingSubjects: "None",
    targetDominance: "pass",
    childSafetyInclusionNote:
      "Neutral unbranded household container with no sharp, hazardous, or readable content.",
    reviewStatus: "approved",
    reviewerNote: iconBatchAApprovalNote,
    provenanceLicenseNote: provenanceNote,
  },
  "word-cat": {
    contentId: "lesson-v1-word-cat",
    targetWord: "cat",
    visualKey: "word-cat",
    visualKind: "image",
    file: "assets/vocabulary/word-cat.webp",
    width: 1254,
    height: 1254,
    byteSize: 55018,
    intendedMeaning: "One friendly house cat.",
    altGuidance: "A single cat silhouette",
    disambiguationNote: "Use one clear cat with no breed-specific distraction.",
    reviewStatus: "approved",
    reviewerNote: batchAReviewNote,
    provenanceLicenseNote: provenanceNote,
  },
  "word-den": {
    contentId: "lesson-v1-word-den",
    targetWord: "den",
    visualKey: "word-den",
    visualKind: "image",
    file: "assets/vocabulary/word-den.webp",
    width: 1254,
    height: 1254,
    byteSize: 85026,
    intendedMeaning: "A fox den opening with one fox.",
    altGuidance: "A fox den opening with one fox",
    disambiguationNote:
      "Keep the den and fox visually clear without extra text; the scene is required by the lesson context.",
    reviewStatus: "approved",
    reviewerNote: batchCApprovalNote,
    provenanceLicenseNote: provenanceNote,
  },
  "word-dog": {
    contentId: "lesson-v1-word-dog",
    targetWord: "dog",
    visualKind: "image",
    visualKey: "word-dog",
    file: "assets/vocabulary/word-dog.webp",
    width: 1254,
    height: 1254,
    byteSize: 53282,
    intendedMeaning: "One friendly dog.",
    altGuidance: "A single dog silhouette",
    disambiguationNote: "Use one clear dog with no breed-specific distraction.",
    reviewStatus: "approved",
    reviewerNote: batchAReviewNote,
    provenanceLicenseNote: provenanceNote,
  },
  "word-dot": {
    contentId: "lesson-v1-word-dot",
    targetWord: "dot",
    visualKey: "word-dot",
    visualKind: "icon",
    file: "assets/vocabulary/word-dot.webp",
    width: 1254,
    height: 1254,
    byteSize: 27584,
    intendedMeaning: "A single dot on a simple map.",
    altGuidance: "A single dot on a simple map",
    disambiguationNote:
      "Show the dot on a map so it is not an isolated meaningless mark.",
    contextualCue:
      "A small blank map provides context while one contrasting dot remains central.",
    dominantVisualSubject: "The single contrasting dot",
    supportingSubjects: "A simple blank map",
    targetDominance: "pass",
    childSafetyInclusionNote:
      "Non-sensitive abstract mark with no text or distracting symbols.",
    reviewStatus: "approved",
    reviewerNote: iconBatchAApprovalNote,
    provenanceLicenseNote: provenanceNote,
  },
  "word-fan": {
    contentId: "lesson-v1-word-fan",
    targetWord: "fan",
    visualKey: "word-fan",
    visualKind: "image",
    file: "assets/vocabulary/word-fan.webp",
    width: 1254,
    height: 1254,
    byteSize: 69538,
    intendedMeaning: "A plain electric fan.",
    altGuidance: "A plain electric fan",
    disambiguationNote:
      "The sentence does not choose handheld or electric; keep the planned electric-fan meaning explicit.",
    reviewStatus: "approved",
    reviewerNote: batchCApprovalNote,
    provenanceLicenseNote: provenanceNote,
  },
  "word-fin": {
    contentId: "lesson-v1-word-fin",
    targetWord: "fin",
    visualKey: "word-fin",
    visualKind: "image",
    file: "assets/vocabulary/word-fin.webp",
    width: 1254,
    height: 1254,
    byteSize: 44672,
    intendedMeaning: "A fish with one fin clearly visible.",
    altGuidance: "A fish with one fin clearly visible",
    disambiguationNote:
      "Keep the fish fin clear and review whether the fin, not only the fish, is immediately named.",
    reviewStatus: "approved",
    reviewerNote: batchCApprovalNote,
    provenanceLicenseNote: provenanceNote,
  },
  "word-gum": {
    contentId: "lesson-v1-word-gum",
    targetWord: "gum",
    visualKey: "word-gum",
    visualKind: "image",
    file: "assets/vocabulary/word-gum.webp",
    width: 1254,
    height: 1254,
    byteSize: 30602,
    intendedMeaning: "A plain wrapped piece of chewing gum.",
    altGuidance: "A plain piece or pack of gum",
    disambiguationNote:
      "Use no brand marks or printed words; do not show gum in a mouth.",
    reviewStatus: "approved",
    reviewerNote: batchCApprovalNote,
    provenanceLicenseNote: provenanceNote,
  },
  "word-gap": {
    contentId: "lesson-v1-word-gap",
    targetWord: "gap",
    visualKey: "word-gap",
    visualKind: "icon",
    file: "assets/vocabulary/word-gap.webp",
    width: 1254,
    height: 1254,
    byteSize: 22900,
    intendedMeaning: "A clear gap in a log.",
    altGuidance: "A clear gap in a log",
    disambiguationNote:
      "Use a broken log shape with strong contrast and no extra clues.",
    contextualCue: "Two log sections frame one broad, clean empty space.",
    dominantVisualSubject: "The broad empty gap between the log sections",
    supportingSubjects: "Two short log sections",
    targetDominance: "pass",
    childSafetyInclusionNote:
      "Neutral natural-material context with no people, animals, or hazards.",
    reviewStatus: "approved",
    reviewerNote: iconBatchAApprovalNote,
    provenanceLicenseNote: provenanceNote,
  },
  "word-hat": {
    contentId: "lesson-v1-word-hat",
    targetWord: "hat",
    visualKind: "image",
    visualKey: "word-hat",
    file: "assets/vocabulary/word-hat.webp",
    width: 1254,
    height: 1254,
    byteSize: 40868,
    intendedMeaning: "A simple broad-brimmed hat.",
    altGuidance: "A simple hat",
    disambiguationNote: "Keep the hat visually distinct from a brimmed cap.",
    reviewStatus: "approved",
    reviewerNote: batchAReviewNote,
    provenanceLicenseNote: provenanceNote,
  },
  "word-jug": {
    contentId: "lesson-v1-word-jug",
    targetWord: "jug",
    visualKind: "image",
    visualKey: "word-jug",
    file: "assets/vocabulary/word-jug.webp",
    width: 1254,
    height: 1254,
    byteSize: 44978,
    intendedMeaning: "A plain handled jug.",
    altGuidance: "A plain handled jug",
    disambiguationNote: "Keep the jug distinct from a mug or cup.",
    reviewStatus: "approved",
    reviewerNote: batchAReviewNote,
    provenanceLicenseNote: provenanceNote,
  },
  "word-mug": {
    contentId: "lesson-v1-word-mug",
    targetWord: "mug",
    visualKey: "word-mug",
    visualKind: "image",
    file: "assets/vocabulary/word-mug.webp",
    width: 1254,
    height: 1254,
    byteSize: 34452,
    intendedMeaning: "A handled drinking mug.",
    altGuidance: "A handled mug on a mat",
    disambiguationNote: "Keep the mug distinct from a jug or cup.",
    reviewStatus: "approved",
    reviewerNote:
      "Isolated mug is clear and matches the approved plan; final accessibility wording remains part of human review.",
    provenanceLicenseNote: provenanceNote,
  },
  "word-pan": {
    contentId: "lesson-v1-word-pan",
    targetWord: "pan",
    visualKey: "word-pan",
    visualKind: "image",
    file: "assets/vocabulary/word-pan.webp",
    width: 1254,
    height: 1254,
    byteSize: 29636,
    intendedMeaning: "A plain shallow cooking pan.",
    altGuidance: "A plain frying pan",
    disambiguationNote: "Keep the handle clear and avoid food text labels.",
    reviewStatus: "approved",
    reviewerNote: batchAReviewNote,
    provenanceLicenseNote: provenanceNote,
  },
  "word-pot": {
    contentId: "lesson-v1-word-pot",
    targetWord: "pot",
    visualKey: "word-pot",
    visualKind: "image",
    file: "assets/vocabulary/word-pot.webp",
    width: 1254,
    height: 1254,
    byteSize: 40108,
    intendedMeaning: "A plain cooking pot with a lid.",
    altGuidance: "A plain cooking pot on a mat",
    disambiguationNote: "Keep the pot distinct from a pan and mug.",
    reviewStatus: "approved",
    reviewerNote:
      "Isolated pot is clear and matches the approved plan; final accessibility wording remains part of human review.",
    provenanceLicenseNote: provenanceNote,
  },
  "word-bun": {
    contentId: "lesson-v1-word-bun",
    targetWord: "bun",
    visualKey: "word-bun",
    visualKind: "image",
    file: "assets/vocabulary/word-bun.webp",
    width: 1254,
    height: 1254,
    byteSize: 36260,
    intendedMeaning: "A plain bread bun.",
    altGuidance: "A plain bread bun",
    disambiguationNote: "Use a bread bun, not a hair bun or a filled pastry.",
    reviewStatus: "approved",
    reviewerNote: batchBReviewNote,
    provenanceLicenseNote: provenanceNote,
  },
  "word-ham": {
    contentId: "lesson-v1-word-ham",
    targetWord: "ham",
    visualKey: "word-ham",
    visualKind: "image",
    file: "assets/vocabulary/word-ham.webp",
    width: 1254,
    height: 1254,
    byteSize: 51534,
    intendedMeaning: "A simple slice of ham.",
    altGuidance: "A simple slice of ham",
    disambiguationNote:
      "Keep the slice plain with no brand, label, or meal context.",
    reviewStatus: "approved",
    reviewerNote: batchBApprovalNote,
    provenanceLicenseNote: provenanceNote,
  },
  "word-hen": {
    contentId: "lesson-v1-word-hen",
    targetWord: "hen",
    visualKey: "word-hen",
    visualKind: "image",
    file: "assets/vocabulary/word-hen.webp",
    width: 1254,
    height: 1254,
    byteSize: 58732,
    intendedMeaning: "One clear hen.",
    altGuidance: "A single hen",
    disambiguationNote:
      "Use one recognizable hen rather than a generic flock or farm scene.",
    reviewStatus: "approved",
    reviewerNote: batchBReviewNote,
    provenanceLicenseNote: provenanceNote,
  },
  "word-hot": {
    contentId: "lesson-v1-word-hot",
    targetWord: "hot",
    visualKey: "word-hot",
    visualKind: "icon",
    file: "assets/vocabulary/word-hot.webp",
    width: 1254,
    height: 1254,
    byteSize: 52748,
    intendedMeaning: "A warm bun with simple heat lines.",
    altGuidance: "A warm bun with simple heat lines",
    disambiguationNote: "Do not rely only on red color to communicate hot.",
    contextualCue:
      "Four large wavy heat lines rise from the bun and carry the state meaning.",
    dominantVisualSubject: "The clear heat lines and hot state",
    supportingSubjects: "One plain bread bun",
    targetDominance: "pass",
    childSafetyInclusionNote:
      "Friendly food-state cue without flames, danger, or injury imagery.",
    reviewStatus: "approved",
    reviewerNote: iconBatchAApprovalNote,
    provenanceLicenseNote: provenanceNote,
  },
  "word-jam": {
    contentId: "lesson-v1-word-jam",
    targetWord: "jam",
    visualKey: "word-jam",
    visualKind: "image",
    file: "assets/vocabulary/word-jam.webp",
    width: 1254,
    height: 1254,
    byteSize: 52774,
    intendedMeaning: "A plain jar of jam.",
    altGuidance: "A plain jar of jam",
    disambiguationNote:
      "Keep the jar free of labels, brand marks, and readable words.",
    reviewStatus: "approved",
    reviewerNote: batchBReviewNote,
    provenanceLicenseNote: provenanceNote,
  },
  "word-jet": {
    contentId: "lesson-v1-word-jet",
    targetWord: "jet",
    visualKey: "word-jet",
    visualKind: "image",
    file: "assets/vocabulary/word-jet.webp",
    width: 1402,
    height: 1122,
    byteSize: 47672,
    intendedMeaning: "A single jet airplane.",
    altGuidance: "A single jet airplane silhouette",
    disambiguationNote:
      "Use one uncluttered jet airplane with no airline logo or text.",
    reviewStatus: "approved",
    reviewerNote: batchBReviewNote,
    provenanceLicenseNote: provenanceNote,
  },
  "word-jog": {
    contentId: "lesson-v1-word-jog",
    targetWord: "jog",
    visualKey: "word-jog",
    visualKind: "icon",
    file: "assets/vocabulary/word-jog.webp",
    width: 1254,
    height: 1254,
    byteSize: 35910,
    intendedMeaning: "A generic figure jogging.",
    altGuidance: "A generic figure jogging",
    disambiguationNote:
      "Show the action clearly without making identity the answer.",
    contextualCue:
      "Separated legs, bent arms, lifted feet, and a forward-leaning mid-stride pose communicate the action.",
    dominantVisualSubject: "The generic jogging body pose",
    supportingSubjects: "One simplified generic figure with no identity cues",
    targetDominance: "pass",
    childSafetyInclusionNote:
      "Featureless rounded head, simple clothing blocks, and no identity, cultural, body-sensitive, or competitive cues.",
    reviewStatus: "needs_review",
    reviewerNote: iconBatchAJogRevisionNote,
    provenanceLicenseNote: provenanceNote,
  },
  "word-leg": {
    contentId: "lesson-v1-word-leg",
    targetWord: "leg",
    visualKey: "word-leg",
    visualKind: "image",
    file: "assets/vocabulary/word-leg.webp",
    width: 1199,
    height: 1312,
    byteSize: 37086,
    intendedMeaning: "A simplified clothed leg.",
    altGuidance: "A simplified clothed leg",
    disambiguationNote:
      "Avoid realistic body detail, nudity, injury, or blood.",
    reviewStatus: "approved",
    reviewerNote: batchCApprovalNote,
    provenanceLicenseNote: provenanceNote,
  },
  "word-lid": {
    contentId: "lesson-v1-word-lid",
    targetWord: "lid",
    visualKey: "word-lid",
    visualKind: "image",
    file: "assets/vocabulary/word-lid.webp",
    width: 1402,
    height: 1122,
    byteSize: 36106,
    intendedMeaning: "A removable cooking-pot lid on a simple pot.",
    altGuidance: "A lid on a pot",
    disambiguationNote:
      "Make the removable lid visually dominant and clear; avoid plate or tray confusion.",
    reviewStatus: "approved",
    reviewerNote: batchCApprovalNote,
    provenanceLicenseNote: provenanceNote,
  },
  "word-log": {
    contentId: "lesson-v1-word-log",
    targetWord: "log",
    visualKey: "word-log",
    visualKind: "image",
    file: "assets/vocabulary/word-log.webp",
    width: 1402,
    height: 1122,
    byteSize: 43310,
    intendedMeaning: "A single log.",
    altGuidance: "A single log in mud",
    disambiguationNote:
      "Keep the log as the clear literal object without written clues or a busy forest scene.",
    reviewStatus: "approved",
    reviewerNote: batchBReviewNote,
    provenanceLicenseNote: provenanceNote,
  },
  "word-lip": {
    contentId: "lesson-v1-word-lip",
    targetWord: "lip",
    visualKey: "word-lip",
    visualKind: "image",
    file: "assets/vocabulary/word-lip.webp",
    width: 1254,
    height: 1254,
    byteSize: 25616,
    intendedMeaning: "A simple lip shape.",
    altGuidance: "A simple lip shape",
    disambiguationNote:
      "Avoid showing the cut from the approved sentence; keep it child-safe and non-medical.",
    reviewStatus: "approved",
    reviewerNote: batchCApprovalNote,
    provenanceLicenseNote: provenanceNote,
  },
  "word-map": {
    contentId: "lesson-v1-word-map",
    targetWord: "map",
    visualKey: "word-map",
    visualKind: "image",
    file: "assets/vocabulary/word-map.webp",
    width: 1254,
    height: 1254,
    byteSize: 26438,
    intendedMeaning: "A folded blank map.",
    altGuidance: "A folded map without readable labels",
    disambiguationNote:
      "Use a folded map with no place names, labels, or other readable text.",
    reviewStatus: "approved",
    reviewerNote: batchBReviewNote,
    provenanceLicenseNote: provenanceNote,
  },
  "word-mat": {
    contentId: "lesson-v1-word-mat",
    targetWord: "mat",
    visualKey: "word-mat",
    visualKind: "image",
    file: "assets/vocabulary/word-mat.webp",
    width: 1536,
    height: 1024,
    intendedMeaning: "A plain floor mat.",
    altGuidance: "A plain floor mat",
    disambiguationNote:
      "Keep the mat plain and visually separate from the background.",
    reviewStatus: "approved",
    byteSize: 78764,
    reviewerNote: batchBApprovalNote,
    provenanceLicenseNote: provenanceNote,
  },
  "word-pen": {
    contentId: "lesson-v1-word-pen",
    targetWord: "pen",
    visualKey: "word-pen",
    visualKind: "image",
    file: "assets/vocabulary/word-pen.webp",
    width: 1254,
    height: 1254,
    byteSize: 27748,
    intendedMeaning: "A simple writing pen.",
    altGuidance: "A simple writing pen",
    disambiguationNote:
      "Use a plain pen without a brand mark, printed word, or extra writing context.",
    reviewStatus: "approved",
    reviewerNote: batchBReviewNote,
    provenanceLicenseNote: provenanceNote,
  },
  "word-pig": {
    contentId: "lesson-v1-word-pig",
    targetWord: "pig",
    visualKey: "word-pig",
    visualKind: "image",
    file: "assets/vocabulary/word-pig.webp",
    width: 1254,
    height: 1254,
    byteSize: 52788,
    intendedMeaning: "A single pig.",
    altGuidance: "A single pig silhouette",
    disambiguationNote:
      "Use one clear pig with no extra action, barn, or farm-scene clue.",
    reviewStatus: "approved",
    reviewerNote: batchBReviewNote,
    provenanceLicenseNote: provenanceNote,
  },
} as const satisfies Record<string, WordRescueAssetReviewRecord>;
