<?php

return [
    'schema_version' => 1,
    'packs' => [
        [
            'pack_id' => 'letters-foundations-v1',
            'version' => '2026.08.2',
            'module_key' => 'letters-set-1',
            'category_key' => 'letters',
            'title' => 'Practice Set 1',
            'minimum_app_version' => '1.0.0',
            'academic_content_language' => 'en',
            'supported_languages' => ['en', 'fil'],
            'status' => 'available',
            'created_at' => '2026-08-10T00:00:00+08:00',
            'updated_at' => '2026-08-10T00:00:00+08:00',
            'source' => [
                'dataset' => 'letters', 'expected_kind' => 'letter',
                'items' => [
                    ['source_content_id' => 'lesson-v1-letter-a', 'practice_item_id' => 'letters-a', 'interaction_mode' => 'letter_read'],
                    ['source_content_id' => 'lesson-v1-letter-b', 'practice_item_id' => 'letters-b', 'interaction_mode' => 'letter_read'],
                    ['source_content_id' => 'lesson-v1-letter-c', 'practice_item_id' => 'letters-c', 'interaction_mode' => 'letter_read'],
                    ['source_content_id' => 'lesson-v1-letter-d', 'practice_item_id' => 'letters-d', 'interaction_mode' => 'letter_read'],
                    ['source_content_id' => 'lesson-v1-letter-e', 'practice_item_id' => 'letters-e', 'interaction_mode' => 'letter_read'],
                    ['source_content_id' => 'lesson-v1-letter-f', 'practice_item_id' => 'letters-f', 'interaction_mode' => 'letter_read'],
                ],
            ],
            'dialogues' => [
                ['dialogue_key' => 'letters-instruction-en', 'language' => 'en', 'speech_key' => 'lesson-1-mission-1', 'text' => 'Look at the big letter and the small letter. Say their letter name.', 'audio_optional' => true],
                ['dialogue_key' => 'letters-instruction-fil', 'language' => 'fil', 'speech_key' => 'lesson-1-mission-1', 'text' => 'Tingnan ang malaking letra at maliit na letra. Sabihin ang pangalan ng letra.', 'audio_optional' => true],
            ],
        ],
        [
            'pack_id' => 'letters-foundations-set-2-v1',
            'version' => '2026.08.1',
            'module_key' => 'letters-set-2',
            'category_key' => 'letters',
            'title' => 'Practice Set 2',
            'minimum_app_version' => '1.0.0',
            'academic_content_language' => 'en',
            'supported_languages' => ['en', 'fil'],
            'status' => 'available',
            'created_at' => '2026-08-10T00:00:00+08:00',
            'updated_at' => '2026-08-10T00:00:00+08:00',
            'source' => [
                'dataset' => 'letters', 'expected_kind' => 'letter',
                'items' => [
                    ['source_content_id' => 'lesson-v1-letter-g', 'practice_item_id' => 'letters-g', 'interaction_mode' => 'letter_read'],
                    ['source_content_id' => 'lesson-v1-letter-h', 'practice_item_id' => 'letters-h', 'interaction_mode' => 'letter_read'],
                    ['source_content_id' => 'lesson-v1-letter-i', 'practice_item_id' => 'letters-i', 'interaction_mode' => 'letter_read'],
                    ['source_content_id' => 'lesson-v1-letter-j', 'practice_item_id' => 'letters-j', 'interaction_mode' => 'letter_read'],
                    ['source_content_id' => 'lesson-v1-letter-k', 'practice_item_id' => 'letters-k', 'interaction_mode' => 'letter_read'],
                    ['source_content_id' => 'lesson-v1-letter-l', 'practice_item_id' => 'letters-l', 'interaction_mode' => 'letter_read'],
                ],
            ],
            'dialogues' => [
                ['dialogue_key' => 'letters-instruction-en', 'language' => 'en', 'speech_key' => 'lesson-1-mission-1', 'text' => 'Look at the big letter and the small letter. Say their letter name.', 'audio_optional' => true],
                ['dialogue_key' => 'letters-instruction-fil', 'language' => 'fil', 'speech_key' => 'lesson-1-mission-1', 'text' => 'Tingnan ang malaking letra at maliit na letra. Sabihin ang pangalan ng letra.', 'audio_optional' => true],
            ],
        ],
        [
            'pack_id' => 'words-foundations-v1',
            'version' => '2026.08.2',
            'module_key' => 'words-set-1',
            'category_key' => 'words',
            'title' => 'Practice Set 1',
            'minimum_app_version' => '1.0.0',
            'academic_content_language' => 'en',
            'supported_languages' => ['en', 'fil'],
            'status' => 'available',
            'created_at' => '2026-08-10T00:00:00+08:00',
            'updated_at' => '2026-08-10T00:00:00+08:00',
            'source' => [
                'dataset' => 'words', 'expected_kind' => 'word',
                'items' => [
                    ['source_content_id' => 'lesson-v1-word-bag', 'practice_item_id' => 'words-bag', 'interaction_mode' => 'word_read'],
                    ['source_content_id' => 'lesson-v1-word-bat', 'practice_item_id' => 'words-bat', 'interaction_mode' => 'word_read'],
                    ['source_content_id' => 'lesson-v1-word-bed', 'practice_item_id' => 'words-bed', 'interaction_mode' => 'word_read'],
                    ['source_content_id' => 'lesson-v1-word-big', 'practice_item_id' => 'words-big', 'interaction_mode' => 'word_read'],
                ],
            ],
            'dialogues' => [
                ['dialogue_key' => 'words-instruction-en', 'language' => 'en', 'speech_key' => 'lesson-2-mission-1', 'text' => 'Read the word you see. Say the whole word.', 'audio_optional' => true],
                ['dialogue_key' => 'words-instruction-fil', 'language' => 'fil', 'speech_key' => 'lesson-2-mission-1', 'text' => 'Basahin ang salitang nakikita mo. Sabihin ang buong salita.', 'audio_optional' => true],
            ],
        ],
        [
            'pack_id' => 'words-foundations-set-2-v1',
            'version' => '2026.08.1',
            'module_key' => 'words-set-2',
            'category_key' => 'words',
            'title' => 'Practice Set 2',
            'minimum_app_version' => '1.0.0',
            'academic_content_language' => 'en',
            'supported_languages' => ['en', 'fil'],
            'status' => 'available',
            'created_at' => '2026-08-10T00:00:00+08:00',
            'updated_at' => '2026-08-10T00:00:00+08:00',
            'source' => [
                'dataset' => 'words', 'expected_kind' => 'word',
                'items' => [
                    ['source_content_id' => 'lesson-v1-word-bun', 'practice_item_id' => 'words-bun', 'interaction_mode' => 'word_read'],
                    ['source_content_id' => 'lesson-v1-word-can', 'practice_item_id' => 'words-can', 'interaction_mode' => 'word_read'],
                    ['source_content_id' => 'lesson-v1-word-cap', 'practice_item_id' => 'words-cap', 'interaction_mode' => 'word_read'],
                    ['source_content_id' => 'lesson-v1-word-cat', 'practice_item_id' => 'words-cat', 'interaction_mode' => 'word_read'],
                ],
            ],
            'dialogues' => [
                ['dialogue_key' => 'words-instruction-en', 'language' => 'en', 'speech_key' => 'lesson-2-mission-1', 'text' => 'Read the word you see. Say the whole word.', 'audio_optional' => true],
                ['dialogue_key' => 'words-instruction-fil', 'language' => 'fil', 'speech_key' => 'lesson-2-mission-1', 'text' => 'Basahin ang salitang nakikita mo. Sabihin ang buong salita.', 'audio_optional' => true],
            ],
        ],
        [
            'pack_id' => 'words-foundations-set-3-v1',
            'version' => '2026.08.1',
            'module_key' => 'words-set-3',
            'category_key' => 'words',
            'title' => 'Practice Set 3',
            'minimum_app_version' => '1.0.0',
            'academic_content_language' => 'en',
            'supported_languages' => ['en', 'fil'],
            'status' => 'available',
            'created_at' => '2026-08-10T00:00:00+08:00',
            'updated_at' => '2026-08-10T00:00:00+08:00',
            'source' => [
                'dataset' => 'words', 'expected_kind' => 'word',
                'items' => [
                    ['source_content_id' => 'lesson-v1-word-cut', 'practice_item_id' => 'words-cut', 'interaction_mode' => 'word_read'],
                    ['source_content_id' => 'lesson-v1-word-dad', 'practice_item_id' => 'words-dad', 'interaction_mode' => 'word_read'],
                    ['source_content_id' => 'lesson-v1-word-den', 'practice_item_id' => 'words-den', 'interaction_mode' => 'word_read'],
                    ['source_content_id' => 'lesson-v1-word-dig', 'practice_item_id' => 'words-dig', 'interaction_mode' => 'word_read'],
                ],
            ],
            'dialogues' => [
                ['dialogue_key' => 'words-instruction-en', 'language' => 'en', 'speech_key' => 'lesson-2-mission-1', 'text' => 'Read the word you see. Say the whole word.', 'audio_optional' => true],
                ['dialogue_key' => 'words-instruction-fil', 'language' => 'fil', 'speech_key' => 'lesson-2-mission-1', 'text' => 'Basahin ang salitang nakikita mo. Sabihin ang buong salita.', 'audio_optional' => true],
            ],
        ],
        [
            'pack_id' => 'phrases-foundations-v1',
            'version' => '2026.08.2',
            'module_key' => 'phrases-set-1',
            'category_key' => 'phrases',
            'title' => 'Practice Set 1',
            'minimum_app_version' => '1.0.0',
            'academic_content_language' => 'en',
            'supported_languages' => ['en', 'fil'],
            'status' => 'available',
            'created_at' => '2026-08-10T00:00:00+08:00',
            'updated_at' => '2026-08-10T00:00:00+08:00',
            'source' => [
                'dataset' => 'phrases', 'expected_kind' => 'phrase',
                'items' => [
                    ['source_content_id' => 'lesson-v1-phrase-big-bag', 'practice_item_id' => 'phrases-big-bag', 'interaction_mode' => 'phrase_read'],
                    ['source_content_id' => 'lesson-v1-phrase-big-dog', 'practice_item_id' => 'phrases-big-dog', 'interaction_mode' => 'phrase_read'],
                    ['source_content_id' => 'lesson-v1-phrase-fat-cat', 'practice_item_id' => 'phrases-fat-cat', 'interaction_mode' => 'phrase_read'],
                    ['source_content_id' => 'lesson-v1-phrase-fat-pig', 'practice_item_id' => 'phrases-fat-pig', 'interaction_mode' => 'phrase_read'],
                ],
            ],
            'dialogues' => [
                ['dialogue_key' => 'phrases-instruction-en', 'language' => 'en', 'speech_key' => 'lesson-3-mission-1', 'text' => 'Read the phrase you see. Say all the words together.', 'audio_optional' => true],
                ['dialogue_key' => 'phrases-instruction-fil', 'language' => 'fil', 'speech_key' => 'lesson-3-mission-1', 'text' => 'Basahin ang pariralang nakikita mo. Sabihin nang magkakasama ang lahat ng salita.', 'audio_optional' => true],
            ],
        ],
        [
            'pack_id' => 'phrases-foundations-set-2-v1',
            'version' => '2026.08.1',
            'module_key' => 'phrases-set-2',
            'category_key' => 'phrases',
            'title' => 'Practice Set 2',
            'minimum_app_version' => '1.0.0',
            'academic_content_language' => 'en',
            'supported_languages' => ['en', 'fil'],
            'status' => 'available',
            'created_at' => '2026-08-10T00:00:00+08:00',
            'updated_at' => '2026-08-10T00:00:00+08:00',
            'source' => [
                'dataset' => 'phrases', 'expected_kind' => 'phrase',
                'items' => [
                    ['source_content_id' => 'lesson-v1-phrase-hot-pan', 'practice_item_id' => 'phrases-hot-pan', 'interaction_mode' => 'phrase_read'],
                    ['source_content_id' => 'lesson-v1-phrase-red-cap', 'practice_item_id' => 'phrases-red-cap', 'interaction_mode' => 'phrase_read'],
                    ['source_content_id' => 'lesson-v1-phrase-red-cup', 'practice_item_id' => 'phrases-red-cup', 'interaction_mode' => 'phrase_read'],
                    ['source_content_id' => 'lesson-v1-phrase-wet-dog', 'practice_item_id' => 'phrases-wet-dog', 'interaction_mode' => 'phrase_read'],
                ],
            ],
            'dialogues' => [
                ['dialogue_key' => 'phrases-instruction-en', 'language' => 'en', 'speech_key' => 'lesson-3-mission-1', 'text' => 'Read the phrase you see. Say all the words together.', 'audio_optional' => true],
                ['dialogue_key' => 'phrases-instruction-fil', 'language' => 'fil', 'speech_key' => 'lesson-3-mission-1', 'text' => 'Basahin ang pariralang nakikita mo. Sabihin nang magkakasama ang lahat ng salita.', 'audio_optional' => true],
            ],
        ],
        [
            'pack_id' => 'sentences-foundations-v1',
            'version' => '2026.08.2',
            'module_key' => 'sentences-set-1',
            'category_key' => 'sentences',
            'title' => 'Practice Set 1',
            'minimum_app_version' => '1.0.0',
            'academic_content_language' => 'en',
            'supported_languages' => ['en', 'fil'],
            'status' => 'available',
            'created_at' => '2026-08-10T00:00:00+08:00',
            'updated_at' => '2026-08-10T00:00:00+08:00',
            'source' => [
                'dataset' => 'sentences', 'expected_kind' => 'sentence',
                'items' => [
                    ['source_content_id' => 'lesson-v1-sentence-big-bag-bed', 'practice_item_id' => 'sentences-big-bag-bed', 'interaction_mode' => 'sentence_read'],
                    ['source_content_id' => 'lesson-v1-sentence-cat-mat', 'practice_item_id' => 'sentences-cat-mat', 'interaction_mode' => 'sentence_read'],
                    ['source_content_id' => 'lesson-v1-sentence-dog-log', 'practice_item_id' => 'sentences-dog-log', 'interaction_mode' => 'sentence_read'],
                ],
            ],
            'dialogues' => [
                ['dialogue_key' => 'sentences-instruction-en', 'language' => 'en', 'speech_key' => 'lesson-4-mission-1', 'text' => 'Read the sentence you see. Say all the words from beginning to end.', 'audio_optional' => true],
                ['dialogue_key' => 'sentences-instruction-fil', 'language' => 'fil', 'speech_key' => 'lesson-4-mission-1', 'text' => 'Basahin ang pangungusap na nakikita mo. Sabihin ang lahat ng salita mula simula hanggang wakas.', 'audio_optional' => true],
            ],
        ],
        [
            'pack_id' => 'sentences-foundations-set-2-v1',
            'version' => '2026.08.1',
            'module_key' => 'sentences-set-2',
            'category_key' => 'sentences',
            'title' => 'Practice Set 2',
            'minimum_app_version' => '1.0.0',
            'academic_content_language' => 'en',
            'supported_languages' => ['en', 'fil'],
            'status' => 'available',
            'created_at' => '2026-08-10T00:00:00+08:00',
            'updated_at' => '2026-08-10T00:00:00+08:00',
            'source' => [
                'dataset' => 'sentences', 'expected_kind' => 'sentence',
                'items' => [
                    ['source_content_id' => 'lesson-v1-sentence-hen-pen', 'practice_item_id' => 'sentences-hen-pen', 'interaction_mode' => 'sentence_read'],
                    ['source_content_id' => 'lesson-v1-sentence-hot-pan-mat', 'practice_item_id' => 'sentences-hot-pan-mat', 'interaction_mode' => 'sentence_read'],
                    ['source_content_id' => 'lesson-v1-sentence-kid-hop', 'practice_item_id' => 'sentences-kid-hop', 'interaction_mode' => 'sentence_read'],
                ],
            ],
            'dialogues' => [
                ['dialogue_key' => 'sentences-instruction-en', 'language' => 'en', 'speech_key' => 'lesson-4-mission-1', 'text' => 'Read the sentence you see. Say all the words from beginning to end.', 'audio_optional' => true],
                ['dialogue_key' => 'sentences-instruction-fil', 'language' => 'fil', 'speech_key' => 'lesson-4-mission-1', 'text' => 'Basahin ang pangungusap na nakikita mo. Sabihin ang lahat ng salita mula simula hanggang wakas.', 'audio_optional' => true],
            ],
        ],
        [
            'pack_id' => 'passages-foundations-v1',
            'version' => '2026.08.2',
            'module_key' => 'passages-set-1',
            'category_key' => 'passages',
            'title' => 'Short Passage 1',
            'minimum_app_version' => '1.0.0',
            'academic_content_language' => 'en',
            'supported_languages' => ['en', 'fil'],
            'status' => 'available',
            'created_at' => '2026-08-10T00:00:00+08:00',
            'updated_at' => '2026-08-10T00:00:00+08:00',
            'source' => [
                'dataset' => 'passages', 'expected_kind' => 'passage',
                'items' => [
                    ['source_content_id' => 'lesson-v1-passage-mila-school', 'practice_item_id' => 'passages-mila-school', 'interaction_mode' => 'passage_read'],
                ],
            ],
            'dialogues' => [
                ['dialogue_key' => 'passages-instruction-en', 'language' => 'en', 'speech_key' => 'lesson-5-mission-1', 'text' => 'Read the passage from beginning to end. Take your time and say every word.', 'audio_optional' => true],
                ['dialogue_key' => 'passages-instruction-fil', 'language' => 'fil', 'speech_key' => 'lesson-5-mission-1', 'text' => 'Basahin ang teksto mula simula hanggang wakas. Huwag magmadali at sabihin ang bawat salita.', 'audio_optional' => true],
            ],
        ],
        [
            'pack_id' => 'passages-foundations-set-2-v1',
            'version' => '2026.08.1',
            'module_key' => 'passages-set-2',
            'category_key' => 'passages',
            'title' => 'Short Passage 2',
            'minimum_app_version' => '1.0.0',
            'academic_content_language' => 'en',
            'supported_languages' => ['en', 'fil'],
            'status' => 'available',
            'created_at' => '2026-08-10T00:00:00+08:00',
            'updated_at' => '2026-08-10T00:00:00+08:00',
            'source' => [
                'dataset' => 'passages', 'expected_kind' => 'passage',
                'items' => [
                    ['source_content_id' => 'lesson-v1-passage-ben-market', 'practice_item_id' => 'passages-ben-market', 'interaction_mode' => 'passage_read'],
                ],
            ],
            'dialogues' => [
                ['dialogue_key' => 'passages-instruction-en', 'language' => 'en', 'speech_key' => 'lesson-5-mission-1', 'text' => 'Read the passage from beginning to end. Take your time and say every word.', 'audio_optional' => true],
                ['dialogue_key' => 'passages-instruction-fil', 'language' => 'fil', 'speech_key' => 'lesson-5-mission-1', 'text' => 'Basahin ang teksto mula simula hanggang wakas. Huwag magmadali at sabihin ang bawat salita.', 'audio_optional' => true],
            ],
        ],
        [
            'pack_id' => 'passages-foundations-set-3-v1',
            'version' => '2026.08.1',
            'module_key' => 'passages-set-3',
            'category_key' => 'passages',
            'title' => 'Short Passage 3',
            'minimum_app_version' => '1.0.0',
            'academic_content_language' => 'en',
            'supported_languages' => ['en', 'fil'],
            'status' => 'available',
            'created_at' => '2026-08-10T00:00:00+08:00',
            'updated_at' => '2026-08-10T00:00:00+08:00',
            'source' => [
                'dataset' => 'passages', 'expected_kind' => 'passage',
                'items' => [
                    ['source_content_id' => 'lesson-v1-passage-lito-beach', 'practice_item_id' => 'passages-lito-beach', 'interaction_mode' => 'passage_read'],
                ],
            ],
            'dialogues' => [
                ['dialogue_key' => 'passages-instruction-en', 'language' => 'en', 'speech_key' => 'lesson-5-mission-1', 'text' => 'Read the passage from beginning to end. Take your time and say every word.', 'audio_optional' => true],
                ['dialogue_key' => 'passages-instruction-fil', 'language' => 'fil', 'speech_key' => 'lesson-5-mission-1', 'text' => 'Basahin ang teksto mula simula hanggang wakas. Huwag magmadali at sabihin ang bawat salita.', 'audio_optional' => true],
            ],
        ],
        [
            'pack_id' => 'comprehension-foundations-v1',
            'version' => '2026.08.2',
            'module_key' => 'comprehension-set-1',
            'category_key' => 'comprehension',
            'title' => 'Practice Set 1',
            'minimum_app_version' => '1.0.0',
            'academic_content_language' => 'en',
            'supported_languages' => ['en', 'fil'],
            'status' => 'available',
            'created_at' => '2026-08-10T00:00:00+08:00',
            'updated_at' => '2026-08-10T00:00:00+08:00',
            'source' => [
                'dataset' => 'comprehension', 'expected_kind' => 'comprehension',
                'items' => [
                    ['source_content_id' => 'lesson-v1-comprehension-who-lena', 'practice_item_id' => 'comprehension-who-lena', 'interaction_mode' => 'comprehension_choice'],
                    ['source_content_id' => 'lesson-v1-comprehension-who-rosa', 'practice_item_id' => 'comprehension-who-rosa', 'interaction_mode' => 'comprehension_choice'],
                    ['source_content_id' => 'lesson-v1-comprehension-what-mia', 'practice_item_id' => 'comprehension-what-mia', 'interaction_mode' => 'comprehension_choice'],
                    ['source_content_id' => 'lesson-v1-comprehension-what-ben', 'practice_item_id' => 'comprehension-what-ben', 'interaction_mode' => 'comprehension_choice'],
                    ['source_content_id' => 'lesson-v1-comprehension-where-cat', 'practice_item_id' => 'comprehension-where-cat', 'interaction_mode' => 'comprehension_choice'],
                ],
            ],
            'dialogues' => [
                ['dialogue_key' => 'comprehension-instruction-en', 'language' => 'en', 'speech_key' => 'lesson-6-mission-1', 'text' => 'Read the sentence, listen to my question, then choose the best answer.', 'audio_optional' => true],
                ['dialogue_key' => 'comprehension-instruction-fil', 'language' => 'fil', 'speech_key' => 'lesson-6-mission-1', 'text' => 'Basahin ang pangungusap, pakinggan ang tanong ko, saka piliin ang pinakamahusay na sagot.', 'audio_optional' => true],
            ],
        ],
        [
            'pack_id' => 'comprehension-foundations-set-2-v1',
            'version' => '2026.08.1',
            'module_key' => 'comprehension-set-2',
            'category_key' => 'comprehension',
            'title' => 'Practice Set 2',
            'minimum_app_version' => '1.0.0',
            'academic_content_language' => 'en',
            'supported_languages' => ['en', 'fil'],
            'status' => 'available',
            'created_at' => '2026-08-10T00:00:00+08:00',
            'updated_at' => '2026-08-10T00:00:00+08:00',
            'source' => [
                'dataset' => 'comprehension', 'expected_kind' => 'comprehension',
                'items' => [
                    ['source_content_id' => 'lesson-v1-comprehension-where-hen', 'practice_item_id' => 'comprehension-where-hen', 'interaction_mode' => 'comprehension_choice'],
                    ['source_content_id' => 'lesson-v1-comprehension-when-lito', 'practice_item_id' => 'comprehension-when-lito', 'interaction_mode' => 'comprehension_choice'],
                    ['source_content_id' => 'lesson-v1-comprehension-when-nena', 'practice_item_id' => 'comprehension-when-nena', 'interaction_mode' => 'comprehension_choice'],
                    ['source_content_id' => 'lesson-v1-comprehension-why-mila', 'practice_item_id' => 'comprehension-why-mila', 'interaction_mode' => 'comprehension_choice'],
                    ['source_content_id' => 'lesson-v1-comprehension-why-tino', 'practice_item_id' => 'comprehension-why-tino', 'interaction_mode' => 'comprehension_choice'],
                ],
            ],
            'dialogues' => [
                ['dialogue_key' => 'comprehension-instruction-en', 'language' => 'en', 'speech_key' => 'lesson-6-mission-1', 'text' => 'Read the sentence, listen to my question, then choose the best answer.', 'audio_optional' => true],
                ['dialogue_key' => 'comprehension-instruction-fil', 'language' => 'fil', 'speech_key' => 'lesson-6-mission-1', 'text' => 'Basahin ang pangungusap, pakinggan ang tanong ko, saka piliin ang pinakamahusay na sagot.', 'audio_optional' => true],
            ],
        ],
    ],
];
