export const GAME_LANGUAGES = ["en", "fil"] as const;

export type GameLanguage = (typeof GAME_LANGUAGES)[number];

export const DEFAULT_LANGUAGE: GameLanguage = "en";
export const LANGUAGE_PREFERENCE_KEY = "readirect-rpg:language-preference:v1";
export const MINIGAME_ID = "chronicles-of-the-lost-kingdom" as const;
export const CONTENT_VERSION_ID = "bilingual-v1" as const;

export type LanguagePreference = {
  version: 1;
  language: GameLanguage;
  minigameId: typeof MINIGAME_ID;
  contentVersion: typeof CONTENT_VERSION_ID;
};

export function isGameLanguage(value: unknown): value is GameLanguage {
  return GAME_LANGUAGES.includes(value as GameLanguage);
}

export function languagePreferenceKey(profileScope = "anonymous") {
  const safeScope = profileScope.replace(/[^a-zA-Z0-9_-]/g, "-").slice(0, 64) || "anonymous";
  return `${LANGUAGE_PREFERENCE_KEY}:${safeScope}`;
}

export function loadLanguagePreference(storage: Storage = window.localStorage, profileScope = "anonymous") {
  try {
    const raw = storage.getItem(languagePreferenceKey(profileScope));
    if (!raw) return null;
    const parsed = JSON.parse(raw) as Partial<LanguagePreference>;
    return parsed.version === 1 && isGameLanguage(parsed.language) ? parsed.language : null;
  } catch {
    return null;
  }
}

export function saveLanguagePreference(language: GameLanguage, storage: Storage = window.localStorage, profileScope = "anonymous") {
  try {
    const value: LanguagePreference = {
      version: 1,
      language,
      minigameId: MINIGAME_ID,
      contentVersion: CONTENT_VERSION_ID
    };
    storage.setItem(languagePreferenceKey(profileScope), JSON.stringify(value));
  } catch {
    // Language remains active for this session when storage is unavailable.
  }
}

export const UI_COPY = {
  en: {
    gameTitle: "Chronicles of the Lost Kingdom",
    shortTitle: "Lost Kingdom",
    phaseLabel: "Phase 3 Reading Activity",
    chooseLanguage: "Choose Your Language",
    languageSupport: "Select the language you want to use in this game.",
    language: "Language",
    changeLanguage: "Change Language",
    continue: "Continue",
    cancel: "Cancel",
    selected: "Selected",
    preparing: "Preparing the adventure",
    loading: "The game foundation is loading.",
    startError: "The game could not start",
    startErrorHelp: "Please try again or return to the temporary dashboard.",
    retry: "Retry",
    exitDashboard: "Exit to Dashboard",
    returnDashboard: "Return to Dashboard",
    sound: "Sound",
    pause: "Pause",
    paused: "Paused",
    hiddenPaused: "Paused while this tab is hidden",
    pauseMessage: "The game is waiting until you continue.",
    resume: "Resume",
    showTutorial: "Show Tutorial",
    exit: "Exit",
    help: "Help",
    interact: "Interact",
    exitTitle: "Exit the minigame?",
    exitDescription: "Your current mission and saved questions will be here when you return.",
    keepPlaying: "Keep Playing",
    currentObjective: "Current mission objective",
    mission: "Mission",
    of: "of",
    missionsComplete: "missions complete",
    question: "Question",
    expandObjective: "Expand objective tracker",
    collapseObjective: "Collapse objective tracker",
    followDots: "Follow the dots",
    openMap: "Open Map",
    closeMap: "Close Map",
    map: "Map",
    pathOn: "Path On",
    pathOff: "Path Off",
    nearby: "Nearby",
    skip: "Skip",
    close: "Close",
    replayVoice: "Replay Voice",
    narrationUnavailable: "Narration unavailable",
    turnVoiceOn: "Turn Voice On",
    mute: "Mute",
    textEffectOff: "Text Effect Off",
    textEffectOn: "Text Effect On",
    readMessage: "Read Message",
    next: "Next",
    previous: "Previous",
    page: "Page",
    purpose: "Purpose",
    ready: "I'm Ready",
    readingActivity: "Story Challenge",
    readingIntro: "Read the short story. Find the clues.",
    startReading: "Open the Story",
    backActivity: "Back to Activity",
    missionDecision: "Mission decision",
    useWhatRead: "Use what you read",
    missionActionComplete: "Mission action complete",
    checkMessage: "Check the message",
    continueQuestions: "Continue to Questions",
    savedLater: "saved for later",
    questionsCompleted: "questions completed",
    correct: "That's right!",
    answerLater: "Answer Later",
    submitAnswer: "Check My Answer",
    tryAgain: "Try Another Clue",
    nextQuestion: "Next Challenge",
    checkUnderstanding: "Story Challenge",
    checkTitle: "Ready for the challenge?",
    checkHelp: "Answer one question at a time. Use what you remember.",
    startQuestions: "Start Questions",
    deferTitle: "Answer this question later?",
    deferHelp: "We'll save it so you can return before finishing the mission.",
    keepAnswering: "Keep Answering",
    saveLater: "Save for Later",
    questionsToAnswer: "Questions to Answer",
    returnTo: "Return to",
    savedQuestionHelp: "Here is your saved question. Use what you remember.",
    returnQuestions: "Return to Questions",
    activityComplete: "Story challenge complete",
    completedQuestions: "You found every story clue!",
    completedQuestionsHelp: "Your answers are saved. See what changed in the village.",
    readingHearts: "Reading hearts",
    heartsRemaining: "hearts remaining",
    heartLost: "One reading heart was used.",
    recoveryTitle: "Let's start this challenge again.",
    recoveryHelp: "Your hearts are back. Try the questions again.",
    viewRecoveryHint: "View Required Clue",
    continueMission: "Continue Mission",
    questionsSaved: "Questions saved for later",
    placeSaved: "Your place is saved",
    answerSavedNowHelp: "Answer now, or return later.",
    answerRemainingHelp: "Would you like to answer them now or continue later?",
    answerNow: "Answer Now",
    continueLater: "Continue Later",
    readingSupport: "Reading support",
    needHint: "Need a hint?",
    helpGuide: "Mission Guide",
    helpCurrentStep: "Do this now",
    helpClue: "Hint",
    helpTryThis: "Try this",
    helpControls: "Quick controls",
    helpKeyboardMove: "WASD or arrow keys",
    helpTouchMove: "D-pad or joystick",
    helpInteractionControl: "Press F or tap Interact",
    helpExploreSteps: [
      "Open the map.",
      "Follow the dots.",
      "Stand near the person. Press Interact."
    ],
    helpReadSteps: [
      "Read the title.",
      "Look for names and places.",
      "Remember the details before you continue."
    ],
    helpActionSteps: [
      "Read the hint.",
      "Check each choice.",
      "Pick the choice from the story."
    ],
    helpQuestionSteps: [
      "Read the question.",
      "Find the answer in the story.",
      "Pick one answer."
    ],
    missionComplete: "complete",
    journeyResult: "Journey result",
    reward: "Reward",
    continueJourney: "Continue Journey",
    openCommunity: "Open Community Activity",
    communityReady: "Community Activity Ready",
    journeyOpen: "The Reading Journey Is Open",
    completionText: "You prepared the central plaza, market, old bridge, and forest route. Every stop is ready.",
    missionsCompleted: "Missions completed",
    skillsUsed: "Reading skills used",
    replayJourney: "Replay Journey",
    answerChoices: "Answer choices",
    tryAnother: "Try another",
    narrator: "Narrator",
    gotIt: "Got it",
    skipTutorial: "Skip Tutorial",
    startAdventure: "Start Adventure",
    skipTutorialTitle: "Skip the tutorial?",
    keepLearning: "Keep Learning",
    noRecording: "No approved narration recording is available for this language.",
    gameHost: "game host",
    guidedTutorial: "Guided tutorial",
    movementControls: "Movement controls",
    movementControlSettings: "Movement control settings",
    movementControlType: "Movement Control",
    useDpad: "Use D-pad",
    useJoystick: "Use Joystick",
    virtualJoystick: "Virtual joystick",
    moveUp: "Move up",
    moveDown: "Move down",
    moveLeft: "Move left",
    moveRight: "Move right"
  },
  fil: {
    gameTitle: "Mga Salaysay ng Nawawalang Kaharian",
    shortTitle: "Nawawalang Kaharian",
    phaseLabel: "Yugto 3 Gawain sa Pagbasa",
    chooseLanguage: "Piliin ang Iyong Wika",
    languageSupport: "Piliin ang wikang gusto mong gamitin sa larong ito.",
    language: "Wika",
    changeLanguage: "Palitan ang Wika",
    continue: "Magpatuloy",
    cancel: "Kanselahin",
    selected: "Napili",
    preparing: "Inihahanda ang pakikipagsapalaran",
    loading: "Inihahanda ang laro.",
    startError: "Hindi nagsimula ang laro",
    startErrorHelp: "Subukan muli o bumalik sa pansamantalang dashboard.",
    retry: "Subukan Muli",
    exitDashboard: "Bumalik sa Dashboard",
    returnDashboard: "Bumalik sa Dashboard",
    sound: "Tunog",
    pause: "I-pause",
    paused: "Naka-pause",
    hiddenPaused: "Naka-pause habang nakatago ang tab na ito",
    pauseMessage: "Naghihintay ang laro hanggang magpatuloy ka.",
    resume: "Magpatuloy",
    showTutorial: "Ipakita ang Tutorial",
    exit: "Lumabas",
    help: "Tulong",
    interact: "Kausapin",
    exitTitle: "Lumabas sa minigame?",
    exitDescription: "Nandito pa rin ang kasalukuyan mong misyon at mga nakalaang tanong pagbalik mo.",
    keepPlaying: "Magpatuloy sa Paglalaro",
    currentObjective: "Kasalukuyang layunin ng misyon",
    mission: "Misyon",
    of: "sa",
    missionsComplete: "misyon ang natapos",
    question: "Tanong",
    expandObjective: "Buksan ang layunin",
    collapseObjective: "Itago ang layunin",
    followDots: "Sundan ang mga tuldok",
    openMap: "Buksan ang Mapa",
    closeMap: "Isara ang Mapa",
    map: "Mapa",
    pathOn: "Gabay Naka-on",
    pathOff: "Gabay Naka-off",
    nearby: "Malapit na",
    skip: "Laktawan",
    close: "Isara",
    replayVoice: "Ulitin ang Boses",
    narrationUnavailable: "Walang salaysay",
    turnVoiceOn: "I-on ang Boses",
    mute: "I-mute",
    textEffectOff: "Patayin ang Epekto",
    textEffectOn: "I-on ang Epekto",
    readMessage: "Basahin ang Mensahe",
    next: "Susunod",
    previous: "Nakaraan",
    page: "Pahina",
    purpose: "Layunin",
    ready: "Handa Na Ako",
    readingActivity: "Hamon sa Kuwento",
    readingIntro: "Basahin ang maikling kuwento. Hanapin ang mga clue.",
    startReading: "Buksan ang Kuwento",
    backActivity: "Bumalik sa Gawain",
    missionDecision: "Pasya sa misyon",
    useWhatRead: "Gamitin ang iyong binasa",
    missionActionComplete: "Tapos na ang gawain sa misyon",
    checkMessage: "Suriin ang mensahe",
    continueQuestions: "Magpatuloy sa mga Tanong",
    savedLater: "nakalaan para mamaya",
    questionsCompleted: "tanong ang natapos",
    correct: "Tama!",
    answerLater: "Sagutin Mamaya",
    submitAnswer: "Suriin ang Sagot Ko",
    tryAgain: "Subukan ang Ibang Clue",
    nextQuestion: "Susunod na Hamon",
    checkUnderstanding: "Hamon sa Kuwento",
    checkTitle: "Handa ka na ba sa hamon?",
    checkHelp: "Sagutin ang isang tanong gamit ang iyong natandaan.",
    startQuestions: "Simulan ang mga Tanong",
    deferTitle: "Sagutin ang tanong na ito mamaya?",
    deferHelp: "Ilalaan namin ito upang mabalikan mo bago matapos ang misyon.",
    keepAnswering: "Ituloy ang Pagsagot",
    saveLater: "Ilaan para Mamaya",
    questionsToAnswer: "Mga Tanong na Sasagutin",
    returnTo: "Bumalik sa",
    savedQuestionHelp: "Narito ang inilaan mong tanong. Gamitin ang iyong natandaan.",
    returnQuestions: "Bumalik sa mga Tanong",
    activityComplete: "Tapos ang hamon sa kuwento",
    completedQuestions: "Nahanap mo ang lahat ng clue sa kuwento!",
    completedQuestionsHelp: "Naitala ang mga sagot. Tingnan ang nagbago sa nayon.",
    readingHearts: "Mga puso sa pagbasa",
    heartsRemaining: "natitirang puso",
    heartLost: "Nagamit ang isang puso sa pagbasa.",
    recoveryTitle: "Simulan nating muli ang hamon.",
    recoveryHelp: "Bumalik ang mga puso mo. Subukan muli ang mga tanong.",
    viewRecoveryHint: "Tingnan ang Kailangang Clue",
    continueMission: "Ipagpatuloy ang Misyon",
    questionsSaved: "Mga tanong na inilaan para mamaya",
    placeSaved: "Naitala ang iyong kinalalagyan",
    answerSavedNowHelp: "Sagutin ngayon, o bumalik mamaya.",
    answerRemainingHelp: "Gusto mo bang sagutin ang mga ito ngayon o magpatuloy mamaya?",
    answerNow: "Sagutin Ngayon",
    continueLater: "Magpatuloy Mamaya",
    readingSupport: "Tulong sa pagbasa",
    needHint: "Kailangan ng pahiwatig?",
    helpGuide: "Gabay sa Misyon",
    helpCurrentStep: "Gawin ngayon",
    helpClue: "Pahiwatig",
    helpTryThis: "Subukan ito",
    helpControls: "Mabilis na kontrol",
    helpKeyboardMove: "WASD o mga arrow key",
    helpTouchMove: "D-pad o joystick",
    helpInteractionControl: "Pindutin ang F o i-tap ang Interact",
    helpExploreSteps: [
      "Buksan ang mapa.",
      "Sundan ang mga tuldok.",
      "Lumapit sa tauhan. Pindutin ang Interact."
    ],
    helpReadSteps: [
      "Basahin ang pamagat.",
      "Hanapin ang mga pangalan at lugar.",
      "Tandaan ang mga detalye bago magpatuloy."
    ],
    helpActionSteps: [
      "Basahin ang pahiwatig.",
      "Tingnan ang bawat sagot.",
      "Piliin ang sagot mula sa kuwento."
    ],
    helpQuestionSteps: [
      "Basahin ang tanong.",
      "Hanapin ang sagot sa kuwento.",
      "Pumili ng isang sagot."
    ],
    missionComplete: "tapos na",
    journeyResult: "Resulta ng paglalakbay",
    reward: "Gantimpala",
    continueJourney: "Ipagpatuloy ang Paglalakbay",
    openCommunity: "Buksan ang Gawain ng Komunidad",
    communityReady: "Handa na ang Gawain ng Komunidad",
    journeyOpen: "Bukas na ang Paglalakbay sa Pagbasa",
    completionText: "Inihanda mo ang liwasan, palengke, lumang tulay, at daan sa gubat. Handa na ang bawat hintuan.",
    missionsCompleted: "Mga natapos na misyon",
    skillsUsed: "Mga kasanayan sa pagbasa",
    replayJourney: "Ulitin ang Paglalakbay",
    answerChoices: "Mga pagpipiliang sagot",
    tryAnother: "Pumili ng iba",
    narrator: "Tagapagsalaysay",
    gotIt: "Naintindihan Ko",
    skipTutorial: "Laktawan ang Tutorial",
    startAdventure: "Simulan ang Pakikipagsapalaran",
    skipTutorialTitle: "Laktawan ang tutorial?",
    keepLearning: "Ipagpatuloy ang Pag-aaral",
    noRecording: "Walang aprubadong salaysay para sa wikang ito.",
    gameHost: "host ng laro",
    guidedTutorial: "Gabay na tutorial",
    movementControls: "Mga kontrol sa paggalaw",
    movementControlSettings: "Mga setting ng kontrol sa paggalaw",
    movementControlType: "Kontrol sa Paggalaw",
    useDpad: "Gamitin ang D-pad",
    useJoystick: "Gamitin ang Joystick",
    virtualJoystick: "Virtual joystick",
    moveUp: "Gumalaw pataas",
    moveDown: "Gumalaw pababa",
    moveLeft: "Gumalaw pakaliwa",
    moveRight: "Gumalaw pakanan"
  }
} as const;

export function getUiCopy(language: GameLanguage) {
  return UI_COPY[language];
}
